"""add_total_dokumen_sesi_chat

Revision ID: 50005a4024fe
Revises: ca39e7878b7f
Create Date: 2026-08-06 15:32:07.468741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50005a4024fe'
down_revision: Union[str, Sequence[str], None] = 'ca39e7878b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('total_dokumen', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('tenants', sa.Column('sesi_chat', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'sesi_chat')
    op.drop_column('tenants', 'total_dokumen')
    # ### end Alembic commands ###
