"""add_roles_and_user_roles

Revision ID: 62e2db92ffe0
Revises: 50005a4024fe
Create Date: 2026-08-11 12:21:47.686122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e2db92ffe0'
down_revision: Union[str, Sequence[str], None] = '50005a4024fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.alter_column('tenants', 'total_dokumen',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tenants', 'sesi_chat',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'sesi_chat',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tenants', 'total_dokumen',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('user_roles')
    # ### end Alembic commands ###
