"""add_chatbot_interactions_table

Revision ID: ca39e7878b7f
Revises: 
Create Date: 2026-08-06 15:19:52.894612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca39e7878b7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot_interactions', sa.Column('intent', sa.String(length=100), nullable=True))
    op.add_column('chatbot_interactions', sa.Column('extra_data', sa.JSON(), nullable=True))
    op.alter_column('chatbot_interactions', 'session_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('chatbot_interactions', 'bot_response',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_chatbot_interactions_session_id'), table_name='chatbot_interactions')
    op.alter_column('data_warga', 'nik',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('data_warga', 'alamat',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_data_warga_nik'), table_name='data_warga')
    op.drop_column('data_warga', 'kecamatan')
    op.drop_column('data_warga', 'rt_rw')
    op.alter_column('knowledge_base', 'kategori',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('tenant_websites', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('tenants', 'sesi_chat')
    op.drop_column('tenants', 'total_dokumen')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('total_dokumen', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('sesi_chat', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.alter_column('tenant_websites', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_base', 'kategori',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('data_warga', sa.Column('rt_rw', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('data_warga', sa.Column('kecamatan', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_data_warga_nik'), 'data_warga', ['nik'], unique=True)
    op.alter_column('data_warga', 'alamat',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('data_warga', 'nik',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.create_index(op.f('ix_chatbot_interactions_session_id'), 'chatbot_interactions', ['session_id'], unique=False)
    op.alter_column('chatbot_interactions', 'bot_response',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('chatbot_interactions', 'session_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('chatbot_interactions', 'extra_data')
    op.drop_column('chatbot_interactions', 'intent')
    # ### end Alembic commands ###
